import { Toaster } from "@/components/ui/toaster";
import "@/styles/globals.css";

import { TRPCReactProvider } from "@/trpc/react";
import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <SessionProvider>
        <body className="min-h-screen bg-background font-sans antialiased">
          <TRPCReactProvider>
            <main className="h-full w-full">{children}</main>
            <Toaster />
          </TRPCReactProvider>
        </body>
      </SessionProvider>
    </html>
  );
}
